import React, {useState} from 'react';
import {createRoot} from 'react-dom/client';
import './style.css';

const ratings=['需要改善','不太滿意','普通','滿意','非常滿意'];
function App(){
 const [name,setName]=useState(''),[department,setDepartment]=useState(''),[rating,setRating]=useState(0),[feedback,setFeedback]=useState(''),[errors,setErrors]=useState({}),[done,setDone]=useState(false);
 const completed=[name.trim(),department,rating].filter(Boolean).length;
 function submit(e){e.preventDefault();const next={};if(!name.trim())next.name='請填寫你的姓名。';if(!department)next.department='請選擇你的科系。';if(!rating)next.rating='請選擇一個滿意度。';setErrors(next);if(Object.keys(next).length){document.getElementById(Object.keys(next)[0]).focus();return;}setDone(true);window.scrollTo({top:0,behavior:'smooth'});}
 return <main className="shell"><header><h1 id="form-title">課程回饋</h1><span className="progress-count" aria-label={`已完成 ${completed} 項必填`}>{done?'完成':`${completed} / 3`}</span></header><div className="progress"><span style={{width:`${completed/3*100}%`}}/></div>{done?<section className="success" role="status"><h2>填寫完成 <span>✓</span></h2><dl><div><dt>姓名</dt><dd>{name.trim()}</dd></div><div><dt>科系</dt><dd>{department}</dd></div><div><dt>滿意度</dt><dd>{rating} / 5 · {ratings[rating-1]}</dd></div><div><dt>意見</dt><dd>{feedback.trim()||'未填寫'}</dd></div></dl><button className="submit" onClick={()=>setDone(false)}>返回修改 <span aria-hidden="true">↗</span></button></section>:<form onSubmit={submit} noValidate><div className="fields"><div className="field"><label htmlFor="name">姓名</label><input id="name" placeholder="輸入姓名" value={name} maxLength={100} autoComplete="name" required onChange={e=>{setName(e.target.value);setErrors({...errors,name:undefined})}} aria-invalid={!!errors.name} aria-describedby={errors.name?'name-error':undefined}/>{errors.name&&<p className="error" id="name-error">{errors.name}</p>}</div><div className="field"><label htmlFor="department">科系</label><select id="department" value={department} required onChange={e=>{setDepartment(e.target.value);setErrors({...errors,department:undefined})}} aria-invalid={!!errors.department} aria-describedby={errors.department?'department-error':undefined}><option value="">選擇科系</option>{['資訊工程系','電子工程系','其他'].map(v=><option key={v}>{v}</option>)}</select>{errors.department&&<p className="error" id="department-error">{errors.department}</p>}</div></div><fieldset><legend>課程滿意度</legend><div className="rating-options" id="rating" tabIndex={-1} role="radiogroup" aria-label="課程滿意度" aria-required="true" aria-describedby={errors.rating?'rating-error':undefined}>{ratings.map((label,i)=><label className={`rating ${rating===i+1?'selected':''}`} key={label}><input type="radio" name="rating" value={i+1} checked={rating===i+1} onChange={()=>{setRating(i+1);setErrors({...errors,rating:undefined})}}/><span className="rating-number">{i+1}</span><span className="rating-label">{label}</span><span className="rating-check" aria-hidden="true">{rating===i+1?'✓':'↗'}</span></label>)}</div>{errors.rating&&<p className="error" id="rating-error">{errors.rating}</p>}</fieldset><div className="field feedback-field"><label htmlFor="feedback">意見回饋 <span>選填</span></label><textarea id="feedback" rows={4} maxLength={1000} placeholder="寫下你的意見或建議" value={feedback} onChange={e=>setFeedback(e.target.value)}/></div><button type="submit" className="submit">送出回饋 <span aria-hidden="true">↗</span></button></form>}<footer>示範表單，資料不會儲存。</footer></main>;
}
createRoot(document.getElementById('root')).render(<App/>);
